### ISSUE TITLE
500 error on login if no user was found for given email address

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Nitro-Backend#49]
**Describe the bug**
If you haven't run the seeds in the backend and you try to log in through your frontend you see:
*Error: GraphQL error: Cannot read property '_fields' of undefined*

**EDIT**: It happens if no user was found for a given email. You can also run the seed data and use a non-existing email address to reproduce the error.

**To Reproduce**
1. Clone the repository, run `docker-compose up`
2. Visit http://localhost:4000/
3. Post following data to endpoint:
```graphql
mutation ($email: String!, $password: String!) {
  login(email: $email, password: $password) {
		token
  }
}
```
with query variables:
```json
{
  "email": "admin@example.org",
   "password": "1234"
}
```
4. See error:
```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "Cannot read property '_fields' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Expected behavior**
4. See error:
```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "There is no user with this email address.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ]
    }
  ]
}
```

**Additional context**
This is how it looks from the frontend:
![screenshot_2018-12-04 human connection - human connection](https://user-images.githubusercontent.com/2110676/49477178-6b6edb00-f81c-11e8-8c9a-91fafe65d4c0.png)

**Comment by appinteractive** [comment]
To say that the password is wrong would be false as is could be also the email. You get what I mean. We have to say that the email and or password are wrong.

**Comment by roschaefer** [comment]
@appinteractive I updated the PR description. By the way: I'm OK with updating PR description in general, so if sth. is missing in future PR descriptions, feel free to update without asking.

**Comment by Kachulio1** [comment]
Can I work on this?

**Comment by appinteractive** [comment]
@Kachulio1 sure, I suspect that one of the middleware is causing that.

**Comment by Gerald1614** [comment]
Hi @Kachulio1 ,
I do not know if you already submitted something to address that but i just find a way to address that. in fact we just need to use a try{} catch{} in the login mutation in graphql-schema.js file. I think it is also a bets practice not to give to many hints to hackers so it would be better to throw the same generic error whatever the username or password failed. (Incorrect username or password.)
I did not wanted to interfere but went through the code and captured that. let me know if you want me to share with you what I did or if you want me to submit a PR for that.

**Comment by appinteractive** [comment]
@Gerald1614 it would be great if you could open a pr with your implantation!

**Comment by appinteractive** [comment]
Hmm 🤔 we have two possibilities:

- translate the api messages in the Frontend 
- translate them in the api by forwarding and respecting the accept-language header. 

For the Frontend solution we could also use custom error types? Translating should then happen not by string but by code for example or providing a translation path. I don’t know which route to take the currently. 

But feel free to open a wip pr and we can discuss it there.

**Comment by roschaefer** [comment]
@Gerald1614 I love it! :+1: 

I vote to translate the error messages in the backend. There are many approaches to it. We could even encode the user's language in the JWT token. How do other people solve it?

**Comment by roschaefer** [comment]
Oh and yes, the fix to the error is trivial but we're currently struggling to [set up tests](https://github.com/Human-Connection/Nitro-Backend/pull/88) for the backend. You're welcome to give it a try :+1:

**Comment by Gerald1614** [comment]
Hi @roschaefer, @appinteractive, i could try starting a test for the login . i see we use Mocha but I also know you mentioned a switch to Jest to use same tool for backend and frontend.  which one would you like us to use?

**Comment by roschaefer** [comment]
@Gerald1614 we already switched from jest to mocha. See here: https://github.com/Human-Connection/Nitro-Backend/pull/88/files I'm struggling with the database environment for testing at the moment. But together with @Kachulio1 and @mattwr18 we came quite far, we could e.g. reproduce the error.

**Comment by Gerald1614** [comment]
@roschaefer, @Kachulio1 , @mattwr18, @appinteractive   I finally came with a working solution to test the backend with Mocha.  it cost me a few hours of sleep that I will pay off tomorrow but I wanted to make it work.
The main issue that I guess we all struggled with is that we try to do a ```request.post('/graphql')``` and we get unauthorised access. this is because the express server is not properly setup,  graphql playground is executed on localhost:4000 and not localhost:4000/graphql like most of applications do. i guess this is something we need to fix. I also had to look in many places to get the right format for the query. so i created a test for a query and another one for a mutation so we have two exemples.
i created a branch were i modified so many things i prefer not to push it but if you already have a branch i could fetch it and commit the following code. please review and feel free to improve, i just put basic checks to make it work. 
```import { describe, it } from 'mocha'
import chai from 'chai'
const url = 'http://localhost:4000'
const request = require('supertest')(url)
const user = { email: 'user@example.org', password: '1234' }
const expect = chai.expect

describe('GraphQL', () => {
  it('Login user id = u3', async () => {
    const res = await request.post('/')
      .set('content-type', 'application/json')
      .send({ query: ' mutation login($email: String!, $password: String!) {user: login(email: $email, password: $password) { id, name, slug, email, token } }',
        variables: {
          'email': user.email,
          'password': user.password
        }
      })
      .expect(200)
    let loggedUser = res.body.data.user
    expect(loggedUser.email).to.equal('user@example.org')
    expect(loggedUser.id).to.equal('u3')
    expect(loggedUser).to.have.property('email')
    expect(loggedUser).to.have.property('token')
  })
  it('get Post id = p1', async () => {
    const res = await request.post('/')
      .set('content-type', 'application/json')
      .send({ query: '{ Post(id: "p1") { id, title } }' })
    let post = res.body.data.Post[0]
    expect(post.id).to.equal('p1')
    expect(post).to.have.property('title')
  })
})```
also we need to be careful checking if we receive a 200 status as it is not always the case. for example, if we want to retrieve a public post but with the email of the author, we still get a response but the status is an error message specifying we are not authorised to access the email of the author.  we can play with those scenarios to create more detailled tests.
no i have to go to bed.

**Comment by appinteractive** [comment]
Many thanks @Gerald1614 ! 👍

I have some questions: 
- What is the exact issue with the url not being /graphql?
- why do you want the email of an author? It will  not be shown for privacy reasons, only for your own user! 
- what was you searching for related to the queries? Wasn’t the api documentation in playground enough? If then what was missing?

Thanks again 🤘 and good night 😴

**Comment by Gerald1614** [comment]
@appinteractive ,
i do not think it is an issue with the url not being /graphql, but my understanding is that usually people are serving  graphql on xxx.xx.xx/port/graphql. It gives you more control on the routes you make available. I know Apollo disables graphql in production i do not know what mecanism it uses, but if it is by preventing people to reach the route then it is better to use a specific route for graphql instead of the root route. in our case I do not think it is intentional as if you look at our server.js file, we try to serve the app through /graphql but obviously it is not working ```server.express.post('/graphql', passport.authenticate(['jwt'], { session: false }))```. the other reason is that if this route is to be used by graphql then maybe it is more explicit to name it like a graphql route. if one day you want to serve other features through the nodejs server it would be easier to get a clean routing.  but once again, i am not a specialist. 
regarding the email of an author, the application is behaving properly. it was just a comment on how we need to be careful with our tests by not always expecting a status 200 as a success. 
for the graphql documentation, it was more small details that made tune the request several times, especially with first attempts, it is not easy to understand if the issue comes from the request itself or the way we try to reach the graphql server, so as  a junior developer, i had to  try a few combinations. it is a great learning curve. I am having pleasure working on this project. I am learning a lot with you guys.
